### ISSUE TITLE
surface.area is zero when the first 3 vertices of the surface are in one line

### ISSUE THREAD

**Issue by VanroyKato** [santoshphilip/eppy#384]
I created a geometry in OpenStudio exported the .idf and wanted to edit some things in python using eppy. 

When creating a geometry in OS apparently the floor vertices aren't simplified and if there are multiple zones adjacent to a wall, it will keep all the coordinates, creating situations where there's 3 or more vertices in one line. 

This causes a problem when wanting to calculate the surface area. I assume the problem is in the unit_normal function since it takes just the 3 first vertices of the surface, returning 0 when these are in one line. 

Example of a surface that caused this problem:  

BuildingSurface:Detailed,
     Face 161,                 !- Name
     Floor,                    !- Surface Type
     Offices_ZN_1_FLR_1_Floor_Ffactor,    !- Construction Name
     Offices_ZN_1_FLR_1,       !- Zone Name
     GroundFCfactorMethod,     !- Outside Boundary Condition
     ,                         !- Outside Boundary Condition Object
     NoSun,                    !- Sun Exposure
     NoWind,                   !- Wind Exposure
     AutoCalculate,            !- View Factor to Ground
     5,                        !- Number of Vertices
     19,                       !- Vertex 1 Xcoordinate
     0,                        !- Vertex 1 Ycoordinate
     0,                        !- Vertex 1 Zcoordinate
     19,                       !- Vertex 2 Xcoordinate
     9,                        !- Vertex 2 Ycoordinate
     0,                        !- Vertex 2 Zcoordinate
     19,                       !- Vertex 3 Xcoordinate
     16.95,                    !- Vertex 3 Ycoordinate
     0,                        !- Vertex 3 Zcoordinate
     45.02,                    !- Vertex 4 Xcoordinate
     16.95,                    !- Vertex 4 Ycoordinate
     0,                        !- Vertex 4 Zcoordinate
     45.02,                    !- Vertex 5 Xcoordinate
     0,                        !- Vertex 5 Ycoordinate
     0;                        !- Vertex 5 Zcoordinate

**Comment by santoshphilip** [comment]
You may have identified the problem correctly. Let me see if the code can be updated to fix that issue.

**Comment by santoshphilip** [comment]
I have fixed this in branch `i384_area`

Once I cleanup the code, I'll merge it into `develop` and `master` branch

Basically I try all the points in the polygon until it hits a non-linear sequence of points. Then it can finish the area calculation. If all points are linear, an area of zero is returned

**Comment by santoshphilip** [comment]
I have made a new release in pipit and in github.
This issue is resolved

**Comment by VanroyKato** [comment]
I updated my eppy version but the bug still seems to be there, the area of surfaces like these still calculates as zero. 

I saw in the tests that a case like this was added, so in theory it should be fine right? But even when I use the coordinates of the test case in my code, it also gives me zero. So I'm not sure what's going on.

**Comment by santoshphilip** [comment]
that's unexpected. I'll check.

**Comment by santoshphilip** [comment]
@VanroyKato , It seems to work on my end. See below. 
Not sure why it is not working for you. Can you show me your code ?

idf file `a.idf`

    Version,
        9.1;                      !- Version Identifier

    BuildingSurface:Detailed,
        Face 161, !- Name
        Floor, !- Surface Type
        Offices_ZN_1_FLR_1_Floor_Ffactor, !- Construction Name
        Offices_ZN_1_FLR_1, !- Zone Name
        GroundFCfactorMethod, !- Outside Boundary Condition
        , !- Outside Boundary Condition Object
        NoSun, !- Sun Exposure
        NoWind, !- Wind Exposure
        AutoCalculate, !- View Factor to Ground
        5, !- Number of Vertices
        19, !- Vertex 1 Xcoordinate
        0, !- Vertex 1 Ycoordinate
        0, !- Vertex 1 Zcoordinate
        19, !- Vertex 2 Xcoordinate
        9, !- Vertex 2 Ycoordinate
        0, !- Vertex 2 Zcoordinate
        19, !- Vertex 3 Xcoordinate
        16.95, !- Vertex 3 Ycoordinate
        0, !- Vertex 3 Zcoordinate
        45.02, !- Vertex 4 Xcoordinate
        16.95, !- Vertex 4 Ycoordinate
        0, !- Vertex 4 Zcoordinate
        45.02, !- Vertex 5 Xcoordinate
        0, !- Vertex 5 Ycoordinate
        0; !- Vertex 5 Zcoordinate

code:

    In [1]: import eppy
    In [2]: idf = eppy.openidf('a.idf')
    In [3]: surfs = idf.idfobjects['BuildingSurface:Detailed']
    In [4]: surf = surfs[0]
    In [7]: surf.area
    Out[7]: 441.03900000000004

**Comment by VanroyKato** [comment]
The first two lines aren't necessarily relevant: I'm just selecting the floor associated to a given construction. 

![Screenshot 2022-05-26 162752](https://user-images.githubusercontent.com/37013382/170574619-b5b2ff8e-b1ff-4b7b-ab18-2cc025740abb.png)

**Comment by santoshphilip** [comment]
I am mystified.
What is your python version?

**Comment by VanroyKato** [comment]
It's 3.8.13

**Comment by santoshphilip** [comment]
OK .. let me try a couple of things

**Comment by santoshphilip** [comment]
Since I can't recreate the error, you will have to help me here.

The code should get to line `58` in `eppy/geometry/surface.py`
Here it calls function `get_an_unit_normal`

The function `get_an_unit_normal` will do the following:
"try all the points in the polygon until it hits a non-linear sequence of points."

It is either not hitting this function OR something is going wrong in the function.

Download the eppy code and put some print statements in  `eppy/geometry/surface.py` to see if you can track down what is going on.

If you are familiar with the python debugger `pdb`, you can use that without downloading the source code. The debugger has a steep learning cure, so don't use it if you have not done it before. (I prefer using print statements)

**Comment by VanroyKato** [comment]
Alright, I'll see if I can find out more!

**Comment by VanroyKato** [comment]
So it turns out I'm not even getting to the line where it calls `get_an_unit_normal `  
I suppose because I'm not getting a ZeroDivisionError but instead the RuntimeWarning
`
![image](https://user-images.githubusercontent.com/37013382/170602541-36c5657b-093e-4609-8db4-d94ab8b305a4.png)

![image](https://user-images.githubusercontent.com/37013382/170602613-48fc6810-0578-449c-b2b7-f44e6226ac88.png)

**Comment by santoshphilip** [comment]
OK ... I think I see where the problem is coming from.

eppy can run with and without numpy installed.
This may give different exceptions or error messages. 

Let me check this out.

**Comment by santoshphilip** [comment]
Yes !!!
if numpy is installed it will give area = 0 (what you have)
without numpy, it will give area = 441.03900000000004

**Comment by santoshphilip** [comment]
I'll work on fixing this.

**Comment by santoshphilip** [comment]
fixed this in issue #386 

Problem: surface.area (for Building:Surface:Detailed) does not work when first 3 points are linear and numpy is installed. 
Solution: This is because numpy does not throw a ZeroDivisionError but raises a RuntimeWarning. Ensure that a ZeroDivisionError is raised in geometry.surface.unit_normal

**Comment by santoshphilip** [comment]
@VanroyKato ,
thanks for your input. You were able to identify why the issue was occurring. That made it easy for me to fix the problem.

**Comment by santoshphilip** [comment]
released a new version on pypi 
new tag on github - this is the latest master
